import { Entity, PrimaryGeneratedColumn, Column, ManyToOne, OneToMany, JoinColumn } from 'typeorm';
// Universal unique identifiers (UUIDs) are a type of user ID that consists of 128-bit numbers. UUIDs are globally unique, meaning there is almost no possibility of generating a duplicate user ID. They are generated by combining time stamps and random information.

@Entity()
export  class Employee {
  @PrimaryGeneratedColumn('uuid')
  id: string; 

  @Column()
  name: string;
  
  @Column()
  description: string; 

  @Column({nullable: true, type: 'uuid'})
  parentId?: string;

  @ManyToOne(() => Employee, (parent) => parent.children, {nullable: true})
  @JoinColumn({name: 'parentId'})
  parent: Employee;

  @OneToMany(() => Employee, (child) => child.parent, { cascade: true })  
  children: Employee[];  
}
